name: release

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: docker.io
  IMAGE_NAME: jrryjcksn/wego-test-app

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
          git fetch --tags -f
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2
      - name: Set env var
        run: |
          make -B dependencies
          echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "FLUX_VERSION=$($(pwd)/tools/bin/stoml $(pwd)/tools/dependencies.toml flux.version)" >> $GITHUB_ENV
          echo "GORELEASER_PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))" >> $GITHUB_ENV
          echo "GORELEASER_CURRENT_TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: "Make All"
        run: make all
      - name: Check Git State
        run: |
          git status
          git diff --no-ext-diff --exit-code
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: "${{ github.workspace }}/.github/changelog/changelog_configuration.json"
          outputFile: "${{ runner.temp }}/changelog.md"
          ignorePreReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --release-notes=${{ runner.temp }}/changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
          BOT_TOKEN: ${{ secrets.WEAVEWORKSBOT_TOKEN }}
          BRANCH: ${{ env.BRANCH }}
          FLUX_VERSION: ${{ env.FLUX_VERSION }}
          GORELEASER_PREVIOUS_TAG: ${{ env.GORELEASER_PREVIOUS_TAG }}
          GORELEASER_CURRENT_TAG: ${{ env.GORELEASER_CURRENT_TAG }}
  publish_npm_package:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
          registry-url: "https://npm.pkg.github.com"
          scope: "@weaveworks"
      - run: npm install
      - run: make ui-lib && cd dist && echo "NPM PUBLISHED"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TEST_TOKEN }}
  build-and-push-image:
    needs: goreleaser
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
          git fetch --tags -f
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
          flavor: |
            latest=true
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: gitops-server.dockerfile
  update-doc-repo-files:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Create GitOps binary
        run: |
          make all
      - name: Set up environment vars
        run: |
          echo "BRANCH=release-doc-updates-$$" >> $GITHUB_ENV
          echo "GITOPS_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Update with new version
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          GA_KEY: ${{ secrets.GA_KEY }}
        run: |
          bash tools/update-docs.sh ${PWD}/bin/gitops ${PWD}/website
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@9825ae65b1cb54b543b938503728b432a0176d29 # v3
        with:
          token: ${{ secrets.TEST_TOKEN }}
          committer: jrryjcksn <jrryjcksn@gmail.com>
          author: jrryjcksn <jrryjcksn@gmail.com>
          signoff: true
          branch: ${{ env.BRANCH }}
          base: main
          title: "Documentation updates for ${{ env.GITOPS_VERSION }}"
          body: "Update version references to ${{ env.GITOPS_VERSION }} and create new versioned documentation set."
